### ISSUE TITLE
重写了css模块，速度提升一倍，支持压缩过的样式，误伤几乎为零

### ISSUE THREAD

**Issue by nuintun** [spmjs/cmd-util#18]
直接上 [性能测试](http://jsperf.com/cmd-css-parser) :smile:  有时间更新到版本库~

样式转换前：

``` css
/*! define a */
@charset "utf-8";
@import url('nav.css');
@import "foot.css";

/* import common.css *//**/

body { color: red; font-size: 12px; }

/* hello world */

/*! block e */
.a { color: black }
/*! endblock */

/*! block f */
.b { color: white }
/*! block g */
.c { color: yellow }
/*! endblock */
.d { color: green }
/*! endblock */
```

新版转换后：

``` css
/*! block a */
@charset "utf-8";
/*! import nav.css */
/*! import foot.css */

/* import common.css *//**/

body { color: red; font-size: 12px; }

/* hello world */

/*! block e */
.a { color: black }
/*! endblock e */

/*! block f */
.b { color: white }
/*! block g */
.c { color: yellow }
/*! endblock g */
.d { color: green }
/*! endblock f */
/*! endblock a */
```

上面样式转换`10000`次新旧效率对比：
![qq20140427174238](https://cloud.githubusercontent.com/assets/1730277/2810872/ad2a47ce-cdf0-11e3-8c4c-4ba81c7a3731.png)
